name: Build and Update Github Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Setup env
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name 'silverster98'
          git config --global user.email '1539168414@qq.com'
          
          npm i
          npm run build

          cp index.html dist/
          cp -r img/ dist/
          cp -r gadget/ dist/
          cp -r project/ dist/

          cd dist
          echo 'silvester.wang' > CNAME
          git init
          git add .
          git commit -m "update at $(date)"
          git remote add origin git@github.com:Silverster98/Silverster98.github.io.git
          git push origin master -f
          